/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_Neuron */

#ifndef _Included_ai_Neuron
#define _Included_ai_Neuron
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_Neuron
 * Method:    activate
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_ai_Neuron_activate
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ai_Neuron
 * Method:    derivative
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_ai_Neuron_derivative
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     ai_Neuron
 * Method:    predict
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ai_Neuron_predict
  (JNIEnv *, jobject);

/*
 * Class:     ai_Neuron
 * Method:    train
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ai_Neuron_train
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ai_Neuron
 * Method:    motivate
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_ai_Neuron_motivate
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     ai_Neuron
 * Method:    importWeights
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_Neuron_importWeights
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ai_Neuron
 * Method:    exportWeights
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_Neuron_exportWeights
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
